name: fluxy
description: "A complete Flutter platform unifying reactive state, declarative UI, styling, animation, routing, and tooling. Build production-grade apps faster and at scale."
version: 0.1.1
homepage: https://github.com/swaingithub/fluxy
repository: https://github.com/swaingithub/fluxy
documentation: https://fluxy-doc.vercel.app/
issue_tracker: https://github.com/swaingithub/fluxy/issues

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.4
  flutter_secure_storage: ^10.0.0
  args: ^2.7.0
  path: ^1.9.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

executables:
  fluxy:
